### ISSUE TITLE
Dataset is not present on provided link. 

### ISSUE THREAD

**Issue by Purnay04** [hoangminhtoan/a2m_osnet_keras#1]
I check the [link](http://www.image-net.org/challenges/LSVRC/2012/nonpub-downloads) you provide in readme but the datatset is not present.
![image_2021-01-21_154237](https://user-images.githubusercontent.com/35885285/105336469-4a85c180-5bff-11eb-958d-66ee57ad36f1.png)

**Comment by hoangminhtoan** [comment]
Hi @Purnay04. I think you need to signup before being able to download dataset. Anyway, for conveting osnet to tflite only, you can check [here](https://github.com/google-coral/edgetpu/issues/290)

**Comment by Purnay04** [comment]
Hello @hoangminhtoan. ![image_2021-01-21_195610](https://user-images.githubusercontent.com/35885285/105364052-b6c5ec80-5c22-11eb-8c8c-a3dd3d7127af.png) 
When i created account and logged in, it is showing me this message. Once i submit the request and re-open the dataset link it again showing me URL is not valid error.

**Comment by hoangminhtoan** [comment]
Hi @Purnay04 
![Screenshot from 2021-01-22 16-51-30](https://user-images.githubusercontent.com/1559257/105462548-1c24e680-5cd2-11eb-813f-571f29452b4c.png)

Anyway, after logging in successfully click on the 'Download' button. My provided URL might be outdated!

**Comment by Purnay04** [comment]
Hello @hoangminhtoan, Sorry for late reply.
As for my project, I'm implementing Person Re-identification using OSNet. For that I'm referencing [this](https://www.kaggle.com/pengcw1/market-1501) dataset which has 1501 classes. I have built my own shards of tfrecords by the help of your modules. but I'm bit confused because every images in this dataset are of 128x64 resolutions. what should I change in OSNet ? So that I can train my model.

**Comment by hoangminhtoan** [comment]
Hi @Purnay04 

You can change the input shape in ```models.py``` as below to suit your project. 

```
IMG_HEIGHT = 256
IMG_WIDTH = 128
IN_SHAPE = (IMG_HEIGHT, IMG_WIDTH, 3) # H, W, C
NUM_CLASSES = 1000 # pretrained imagenet has 1000 classes
```
